//
// Autogenerated by Thrift Compiler (0.11.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
"use strict";

var thrift = require('thrift');
var Thrift = thrift.Thrift;
var Q = thrift.Q;


var ttypes = require('./serviceIDL_types');
//HELPER FUNCTIONS AND STRUCTURES

var ServiceCaller_INVOKE_args = function(args) {
  this.params = null;
  if (args) {
    if (args.params !== undefined && args.params !== null) {
      this.params = new ttypes.Params(args.params);
    }
  }
};
ServiceCaller_INVOKE_args.prototype = {};
ServiceCaller_INVOKE_args.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
      if (ftype == Thrift.Type.STRUCT) {
        this.params = new ttypes.Params();
        this.params.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ServiceCaller_INVOKE_args.prototype.write = function(output) {
  output.writeStructBegin('ServiceCaller_INVOKE_args');
  if (this.params !== null && this.params !== undefined) {
    output.writeFieldBegin('params', Thrift.Type.STRUCT, 1);
    this.params.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ServiceCaller_INVOKE_result = function(args) {
  this.success = null;
  if (args) {
    if (args.success !== undefined && args.success !== null) {
      this.success = new ttypes.Params(args.success);
    }
  }
};
ServiceCaller_INVOKE_result.prototype = {};
ServiceCaller_INVOKE_result.prototype.read = function(input) {
  input.readStructBegin();
  while (true)
  {
    var ret = input.readFieldBegin();
    var fname = ret.fname;
    var ftype = ret.ftype;
    var fid = ret.fid;
    if (ftype == Thrift.Type.STOP) {
      break;
    }
    switch (fid)
    {
      case 0:
      if (ftype == Thrift.Type.STRUCT) {
        this.success = new ttypes.Params();
        this.success.read(input);
      } else {
        input.skip(ftype);
      }
      break;
      case 0:
        input.skip(ftype);
        break;
      default:
        input.skip(ftype);
    }
    input.readFieldEnd();
  }
  input.readStructEnd();
  return;
};

ServiceCaller_INVOKE_result.prototype.write = function(output) {
  output.writeStructBegin('ServiceCaller_INVOKE_result');
  if (this.success !== null && this.success !== undefined) {
    output.writeFieldBegin('success', Thrift.Type.STRUCT, 0);
    this.success.write(output);
    output.writeFieldEnd();
  }
  output.writeFieldStop();
  output.writeStructEnd();
  return;
};

var ServiceCallerClient = exports.Client = function(output, pClass) {
    this.output = output;
    this.pClass = pClass;
    this._seqid = 0;
    this._reqs = {};
};
ServiceCallerClient.prototype = {};
ServiceCallerClient.prototype.seqid = function() { return this._seqid; };
ServiceCallerClient.prototype.new_seqid = function() { return this._seqid += 1; };
ServiceCallerClient.prototype.INVOKE = function(params, callback) {
  this._seqid = this.new_seqid();
  if (callback === undefined) {
    var _defer = Q.defer();
    this._reqs[this.seqid()] = function(error, result) {
      if (error) {
        _defer.reject(error);
      } else {
        _defer.resolve(result);
      }
    };
    this.send_INVOKE(params);
    return _defer.promise;
  } else {
    this._reqs[this.seqid()] = callback;
    this.send_INVOKE(params);
  }
};

ServiceCallerClient.prototype.send_INVOKE = function(params) {
  var output = new this.pClass(this.output);
  output.writeMessageBegin('INVOKE', Thrift.MessageType.CALL, this.seqid());
  var params = {
    params: params
  };
  var args = new ServiceCaller_INVOKE_args(params);
  args.write(output);
  output.writeMessageEnd();
  return this.output.flush();
};

ServiceCallerClient.prototype.recv_INVOKE = function(input,mtype,rseqid) {
  var callback = this._reqs[rseqid] || function() {};
  delete this._reqs[rseqid];
  if (mtype == Thrift.MessageType.EXCEPTION) {
    var x = new Thrift.TApplicationException();
    x.read(input);
    input.readMessageEnd();
    return callback(x);
  }
  var result = new ServiceCaller_INVOKE_result();
  result.read(input);
  input.readMessageEnd();

  if (null !== result.success) {
    return callback(null, result.success);
  }
  return callback('INVOKE failed: unknown result');
};
var ServiceCallerProcessor = exports.Processor = function(handler) {
  this._handler = handler;
}
;
ServiceCallerProcessor.prototype.process = function(input, output) {
  var r = input.readMessageBegin();
  if (this['process_' + r.fname]) {
    return this['process_' + r.fname].call(this, r.rseqid, input, output);
  } else {
    input.skip(Thrift.Type.STRUCT);
    input.readMessageEnd();
    var x = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN_METHOD, 'Unknown function ' + r.fname);
    output.writeMessageBegin(r.fname, Thrift.MessageType.EXCEPTION, r.rseqid);
    x.write(output);
    output.writeMessageEnd();
    output.flush();
  }
}
;
ServiceCallerProcessor.prototype.process_INVOKE = function(seqid, input, output) {
  var args = new ServiceCaller_INVOKE_args();
  args.read(input);
  input.readMessageEnd();
  if (this._handler.INVOKE.length === 1) {
    Q.fcall(this._handler.INVOKE.bind(this._handler), args.params)
      .then(function(result) {
        var result_obj = new ServiceCaller_INVOKE_result({success: result});
        output.writeMessageBegin("INVOKE", Thrift.MessageType.REPLY, seqid);
        result_obj.write(output);
        output.writeMessageEnd();
        output.flush();
      }, function (err) {
        var result;
        result = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("INVOKE", Thrift.MessageType.EXCEPTION, seqid);
        result.write(output);
        output.writeMessageEnd();
        output.flush();
      });
  } else {
    this._handler.INVOKE(args.params, function (err, result) {
      var result_obj;
      if ((err === null || typeof err === 'undefined')) {
        result_obj = new ServiceCaller_INVOKE_result((err !== null || typeof err === 'undefined') ? err : {success: result});
        output.writeMessageBegin("INVOKE", Thrift.MessageType.REPLY, seqid);
      } else {
        result_obj = new Thrift.TApplicationException(Thrift.TApplicationExceptionType.UNKNOWN, err.message);
        output.writeMessageBegin("INVOKE", Thrift.MessageType.EXCEPTION, seqid);
      }
      result_obj.write(output);
      output.writeMessageEnd();
      output.flush();
    });
  }
};
