/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package Poseidon.ServiceDefine;


public enum ParamType implements org.apache.thrift.TEnum {
  INT(1),
  FLOAT(2),
  BOOL(3),
  STRING(4),
  LIST(10),
  MAP(11);

  private final int value;

  private ParamType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ParamType findByValue(int value) { 
    switch (value) {
      case 1:
        return INT;
      case 2:
        return FLOAT;
      case 3:
        return BOOL;
      case 4:
        return STRING;
      case 10:
        return LIST;
      case 11:
        return MAP;
      default:
        return null;
    }
  }
}
